export const GET_TRACKS_START = "GET_TRACKS_START";
export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS";
export const GET_TRACKS_FAILURE = "GET_TRACKS_FAILURE";

export const SEARCH_TRACKS_START = "SEARCH_TRACKS_START";
export const SEARCH_TRACKS_SUCCESS = "SEARCH_TRACKS_SUCCESS";
export const SEARCH_TRACKS_FAILURE = "SEARCH_TRACKS_FAILURE";

export const GET_ARTIST_START = "GET_ARTIST_START";
export const GET_ARTIST_SUCCESS = "GET_ARTIST_SUCCESS";
export const GET_ARTIST_FAILURE = "GET_ARTIST_FAILURE";

export const LOADMORE_TRACKS_START = "LOADMORE_TRACKS_START";
export const LOADMORE_TRACKS_SUCCESS = "LOADMORE_TRACKS_SUCCESS";
export const LOADMORE_TRACKS_FAILURE = "LOADMORE_TRACKS_FAILURE";
